export const ROUTES = {
  ENTRY: "*",
  LOGIN: "/logIn",
  SIGNUP: "/signUp",
  ELADJEWELRY: `/elad's_jewelry`,
  PRODUCTS: "products",
  RINGS: "rings",
  EARRINGS: "earrings",
  NECKLACES: "necklaces",
  BRACELETS: "bracelets",
  CART: "cart",
  SEARCH: "search",
  PROFILE: "profile",
  PURCHES: "purches",
  EDIT: "edit",
  DELETEACCOUNT: "deleteAccount",
  VIEWPURCHASES: "viewPurchases",
  DATA: "data",
  USERSCEO: "usersCEO",
  PRODUCTSCEO: "productsCEO",
  ADDPRODUCTS: "addProducts",
  LIST_OF_DELETING_PRODUCTS: "listOfdeletingProducts",
  LIST_OF_ALL_USERS: "listOfUsers",
  LIST_OF_DELETING_USERS: "listOfDeletingUsers",
  EDITPRODUCT: "/editProduct",
};
